### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-watchlist#1]
Hi, gehe ich recht in der Annahme, dass diese Erweiterung eine Liste der beliebtesten Downloads erzeugt oder welche Funktio verbirgt sich genau hinter der "Watchlist"?

**Comment by fatcrobat** [comment]
Hallo,

die Dokumentation ist in der Tat etwas dürftig. Die Erweiterung stellt ein Modul bereit, dass ähnlich eines Leuchtkastens funktioniert. Man kann damit einzelne Downloads zur Merkliste hinzufügen und auch wieder entfernen. Weiterhin kann man alle Dateien aus der Merkliste entfernen und auf einmal alle Dateien in einem Zip-Archiv herunterladen.

**Comment by operatorone** [comment]
Ah, verstehe. Vielen Dank für die Rückmeldung. Ich suche eher eine Erweiterung die es mir ermöglicht eine Liste der "Beliebtesten Downloads" zu erzeugen, sprich die am häufigsten heruntergeladenen. Haben Sie ggf. dazu eine Idee? Vielleicht so zufaällig? ;-)

**Comment by fatcrobat** [comment]
Leider nein. Aber im Grunde müsstest du dich nur in den `$GLOBALS['TL_HOOKS']['postDownload']` bevor die Datei heruntergeladen wird und in der tl_files Datenbank in einem neuen Feld `downloads` den Wert um 1 hochzählen. ;) Der Aufwand dafür sollte sich im Rahmen halten.

**Comment by operatorone** [comment]
Superklasse. Danke für den Tip :-)
